### ISSUE TITLE
TODO Ideas to improve this shit

### ISSUE THREAD

**Issue by s1nn105** [s1nn105/eiertauschClone#1]
## Ideas / TODOS that could and should be done but are not really neccessary right now
- [ ]  tilemap as a class in (GameEngine.js) therefore the issues with checking for conditions is simplified. simpler to access
- [ ]  only one method on interval that handels all the shit
- [ ]  add an empty piece in pieces.js
- [ ]  add animations. This also simplifies the debug process because eg. you see where the pieces drop to (currently to the side i think)
- [ ]  clean up the code and document it better.
